const prefix = 'App'

export const FETCH_BONUS_CONDITIONS_SUCCESS = prefix + '/FETCH_BONUS_CONDITIONS_SUCCESS';
export const FETCH_BONUS_CONDITIONS_FAILURE = prefix + '/FETCH_BONUS_CONDITIONS_FAILURE';