const prefix = 'CompanyWebsite'

export const FETCH_WEBSITE_BEFORE = prefix + '/FETCH_WEBSITE_BEFORE';
export const FETCH_WEBSITE_SUCCESS = prefix + '/FETCH_WEBSITE_SUCCESS';
export const FETCH_WEBSITE_FAILURE = prefix + '/FETCH_WEBSITE_FAILURE';

export const SAVE_WEBSITE_BEFORE = prefix + '/SAVE_WEBSITE_BEFORE';
export const SAVE_WEBSITE_SUCCESS = prefix + '/SAVE_WEBSITE_SUCCESS';
export const SAVE_WEBSITE_FAILURE = prefix + '/SAVE_WEBSITE_FAILURE';

export const VALIDATE_WEBSITE_REQUEST = prefix + '/VALIDATE_WEBSITE_REQUEST';
export const VALIDATE_WEBSITE_SUCCESS = prefix + '/VALIDATE_WEBSITE_SUCCESS';
export const VALIDATE_WEBSITE_FAILURE = prefix + '/VALIDATE_WEBSITE_FAILURE';

export const WEBSITE_CHANGED = prefix + '/WEBSITE_CHANGED';
